### ISSUE TITLE
can't seem to run the 'make-file' 

### ISSUE THREAD

**Issue by booikluiving** [ezrec/epson-tm-c610#2]
Hello,

I'm trying to install this driver but i'm stuck at the 'make' command.

if I do **sudo make -f epson-tm-c610-master/Makefile**

I get **make: *** No rule to make target `ep_tmc6xx.drv', needed by `ppd/ep_tmc610.ppd'.  Stop.**

Any idea why this happens? I don't have a ppd folder in my **usr/share**, maybe that's the problem? Or do i need to change the make file or put the files in another directory? 

Thanks in advance!

**Comment by ezrec** [comment]
You need to `cd epson-tm-c610-master` before `sudo make install`

**Comment by booikluiving** [comment]
Thanks! Seems to work! But now i get this Error:

rastertotmc6xx.c:14:10: fatal error: 'cups/i18n.h' file not found
#include <cups/i18n.h>

**Comment by ezrec** [comment]
`sudo apt install libcups2-dev`

**Comment by ezrec** [comment]
Ooh. May be some issues after that. I need to update the code a bit for current libcups2

**Comment by ezrec** [comment]
Re-pull master, it should now at least _compile_.

**Comment by booikluiving** [comment]
Still at libcups2-dev, i'm on a mac and can't install it with brew..

**Comment by ezrec** [comment]
Hmm. Not a mac user, but can you install XCode and add the Cups development dependencies?

**Comment by booikluiving** [comment]
Installed Xcode, I don't know what you mean with _Cups development dependencies_..  
Everywhere I look Cups related code seems to be based on Linux..
Starting to think this one is gonna be impossible with a mac.
Also I have a TM-c700, which may not even work with the code you have here..

**Comment by booikluiving** [comment]
gonna try on a different OS so I'm closing
